// <auto-generated />
namespace D40.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ticketassetfkey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ticketassetfkey));
        
        string IMigrationMetadata.Id
        {
            get { return "201708081502147_ticket asset fkey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
